package com.acc.constants;

public class CommonConstants {
	public static final String GET_ACCOUNT_LIST_HTM = "getAccountList.htm";
	public static final String GET_UNDER_WRITER_HTM = "getUnderWriter.htm";
	public static final String VIRTUAL_MAIN_BACK_HTM = "virtualMainBack.htm";
	public static final String VIRTUAL_MAIN_HTM = "virtualMain.htm";
	public static final String ERROR_JSP = "error.jsp";
	public static final String APPLICATION_JSON = "application/json";
	public static final String VIRTUAL_MAIN = "virtualMain";
	public static final String ACCOUNT_LIST = "accountList";
	public static final String UNDER_WRITER_LIST = "underWriterList";
	public static final String PRODUCT_TYPE = "productType";
	public static final String COVERAGE_TYPE = "coverageType";
	public static final String DOC_LIST = "DocList";
	public static final String REVIEWER_LIST = "reviewerList";
	public static final String UNDER_WRITER_ID = "underWriterId";
	public static final String ID = "id";
	public static final String A_LIST = "aList";
	public static final String U_LIST = "uList";
	public static final String URL = "url";
	public static final String EXCEPTION = "exception";
	public static final String ERROR_OCCURRED = "ERROR OCCURRED";
	public static final String ERR_MSG = "errMsg";
	public static final String SUCCESS = "success";
	public static final String ACCOUNT_SAVE_HTM = "accountSave.htm";
	public static final String ACCOUNT_INFO = "accountInfo";
	public static final String ACCOUNT_INFO_HTM = "accountInfo.htm";
	public static final String ACCID = "accid";
	public static final String FROM_DOC_REV_STATUS = "from DocRevStatus";
	public static final String FROM_ACCOUNT = "from Account";
	public static final String FROM_ACCOUNT_UW_MAPPING_M_ORDER_BY_M_ACCOUNT_ACCOUNT_ID_DESC = "from Account_UW_Mapping m ORDER BY m.account.account_Id DESC";
	public static final String FROM_UW_MAPPING_U_ORDER_BY_U_UW_MAPPING_ID_ASC = "from UW_Mapping u ORDER BY u.uw_Mapping_Id  ASC";
	public static final String ID2 = "id";
	public static final String GENERIC_ERROR = "generic_error";
	public static final String UNCHECKED = "unchecked";
	public static final String EXCEPTION_MESSAGE = "Exception Message is :";
	public static final String TEAM5 = "Team5";
	public static final String TEAM4 = "Team4";
	public static final String TEAM3 = "Team3";
	public static final String TEAM2 = "Team2";
	public static final String TEAM1 = "Team1";
	public static final String INCORRECT = "Incorrect";
	public static final String MISSING = "Missing";
	public static final String INCOMPLETE = "Incomplete";
}
